server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;

    location /dashboard/ {
        alias /usr/share/nginx/html/dashboard/;
        index index.html;
        try_files $uri $uri/ @spa;
    }

    location @spa {
        root /usr/share/nginx/html;
        rewrite ^.* /dashboard/index.html break;
    }
}